sudo: required
services:
  - docker

before_install:
  - docker build -t paccydocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true paccydocker/react-test npm test -- --coverage

after_success:
  - docker build -t paccydocker/multi-client ./client
  - docker build -t paccydocker/multi-nginx ./nginx
  - docker build -t paccydocker/multi-server ./server
  - docker build -t paccydocker/multi-worker ./worker

  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push paccydocker/multi-client
  - docker push paccydocker/multi-nginx
  - docker push paccydocker/multi-server
  - docker push paccydocker/multi-worker
